TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devtmo_coupler.db
DB_INSTALLS += $(TOP)/tmo_couplerSup/devtmo_coupler.proto

#=======================================
include $(TOP)/configure/RULES
